version: "3.4"
services:
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EULA: true
        NEOFORGE_VERSION: 1.20.1-47.1.103
        MODPACK_VERSION: 1.0.0
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8100:8100'
    expose:
      - 25565
      - 25575
      - 8100
    tty: false
