version: "3.4"
services:
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '25565:25565'
      - '8100:8100'
    expose:
      - 25565
      - 8100
    tty: false
